-- game-reports D1 schema
--
-- A transient inbox: mobile games POST reports here, the Auto Game Builder
-- backend pulls them and then DELETEs them (rows + their R2 screenshots), so
-- this table normally holds only what has not yet been collected. AGB is the
-- durable archive, not this.

CREATE TABLE IF NOT EXISTS reports (
  id           TEXT PRIMARY KEY,      -- uuid v4, generated by the worker
  received_at  INTEGER NOT NULL,      -- epoch ms the worker accepted it
  package      TEXT NOT NULL,         -- e.g. com.lifecharger.arcadesnake
  category     TEXT NOT NULL,         -- bug | suggestion | other
  message      TEXT NOT NULL,         -- user-typed text
  app_version  TEXT,                  -- client app version string
  platform     TEXT,                  -- android | ios | ...
  install_id   TEXT,                  -- random per-install id (not a user id)
  shots        TEXT NOT NULL DEFAULT '[]', -- JSON array of R2 object keys
  meta         TEXT NOT NULL DEFAULT '{}'  -- JSON: device brand/model, os version, sdk, etc.
);

CREATE INDEX IF NOT EXISTS idx_reports_received ON reports (received_at);
CREATE INDEX IF NOT EXISTS idx_reports_install ON reports (install_id);
